name: acts-pr-cpu
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - cpuonly=2.0
  - pytorch=2.1.0
  - torchvision=0.16.0
  - torchaudio=2.1.0
  - pip=23.3.1
  - pip:
    - pytorch-lightning==2.1.0
    - lightning
    - tensorboard==2.14.1
    - tabulate>=0.8.9
    - tqdm>=4.62.3
    - pillow>=8.0.1
    - notebook>=6.4.5
    - jupyterlab>=3.2.1
    - matplotlib>=3.4.3
    - seaborn>=0.11.2
    - ipywidgets>=7.6.5
